(function(){
  const state={selected:null,expected:[],overrides:[]};
  const isTime=e=>['100m','400m','110mh','1500m','100mh','200m','800m'].includes(e);
  const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function birth(v){const s=String(v||'').trim();if(!s)return'';const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}.${m[2]}.${m[1]}`:s;}
  function predicted(entries,event){const vals=(Array.isArray(entries)?entries:[]).map(r=>Number(r.mark)).filter(Number.isFinite).sort((a,b)=>isTime(event)?a-b:b-a);const used=vals.length>=4?vals.slice(0,3):vals;if(!used.length)return null;return used.reduce((s,v)=>s+v,0)/used.length;}
  function fmt(event,v){if(v==null||!Number.isFinite(Number(v)))return '—';if(event==='1500m'||event==='800m'){const n=Number(v),m=Math.floor(n/60),s=(n-m*60).toFixed(2).padStart(5,'0');return `${m}:${s}`.replace('.',',');}return Number(v).toFixed(2).replace('.',',');}
  function parseInput(event,v){const s=String(v||'').trim().replace(',','.');if(!s)return null;if((event==='1500m'||event==='800m')&&s.includes(':')){const p=s.split(':').map(Number);if(p.length===2&&p.every(Number.isFinite))return p[0]*60+p[1];}const n=Number(s);return Number.isFinite(n)?n:null;}
  function hasOverride(v){return v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));}
  function expectedTotal(values){let sum=0;for(let i=0;i<D.events.length;i++){const v=values[i];if(v==null||!Number.isFinite(Number(v)))return null;const pts=scoreEvent(i,Number(v));if(!Number.isFinite(Number(pts)))return null;sum+=Number(pts);}return sum;}
  function currentValues(){return D.events.map((ev,i)=>hasOverride(state.overrides[i])?Number(state.overrides[i]):state.expected[i]);}
  function basisColor(n){if(n>=4)return '#39d98a';if(n===3)return '#fff176';if(n===2)return '#ff9f43';if(n===1)return '#ff5b5b';return '#9fb2c6';}
  function inject(){const panel=document.querySelector('#forecast');if(!panel||document.querySelector('#athleteCompareBox'))return;const box=document.createElement('div');box.id='athleteCompareBox';box.style.cssText='margin-top:22px;border:1px solid #294d6c;border-radius:12px;background:#0a1d31;padding:18px';box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap"><div><h3 style="margin:0 0 6px">Sammenlign med en annen utøver</h3><p style="margin:0;color:#9fb2c6">Søk på navn. Bare utøvere med ${currentType==='women'?'sjukamp':'tikamp'}resultater vises.</p></div></div><div style="position:relative;max-width:620px;margin-top:14px"><div style="display:flex;gap:8px"><input id="athleteCompareSearch" autocomplete="off" placeholder="Skriv navn, f.eks. Jonathan Hertwig" style="flex:1;min-width:0;padding:12px 14px;border-radius:8px;border:1px solid #456783;background:#07182b;color:#fff;font-size:16px"><button id="athleteCompareBtn" type="button" style="padding:10px 16px;border:0;border-radius:8px;background:#6f4cff;color:#fff;font-weight:800;cursor:pointer">Søk</button></div><div id="athleteCompareResults" style="display:none;position:absolute;z-index:30;left:0;right:0;top:50px;background:#0c243d;border:1px solid #456783;border-radius:8px;overflow:hidden;box-shadow:0 12px 28px #0008"></div></div><div id="athleteCompareStatus" style="margin-top:10px;color:#9fb2c6"></div><div id="athleteCompareOutput" style="margin-top:14px"></div>`;panel.appendChild(box);
    document.querySelector('#athleteCompareBtn').onclick=search;
    document.querySelector('#athleteCompareSearch').addEventListener('keydown',ev=>{if(ev.key==='Enter'){ev.preventDefault();search();}});
  }
  async function search(){const input=document.querySelector('#athleteCompareSearch'),q=input?.value?.trim(),status=document.querySelector('#athleteCompareStatus'),results=document.querySelector('#athleteCompareResults');if(!q||q.length<2)return;status.textContent='Søker etter utøver…';results.style.display='none';try{const r=await fetch(`/api/athlete-search?action=search&type=${encodeURIComponent(currentType)}&q=${encodeURIComponent(q)}`,{cache:'no-store'}),data=await r.json();if(!r.ok)throw new Error(data.error||'Søket mislyktes');const list=data.athletes||[];status.textContent=list.length?'Velg riktig utøver:':'Ingen relevante mangekamputøvere funnet.';if(!list.length)return;results.innerHTML=list.map(a=>`<button type="button" data-id="${e(a.id)}" data-name="${e(a.name)}" style="display:block;width:100%;text-align:left;padding:12px 14px;border:0;border-bottom:1px solid #1f405d;background:#0c243d;color:#fff;cursor:pointer"><b>${e(a.name)}</b><span style="display:block;color:#9fb2c6;font-size:13px;margin-top:2px">${e(a.nation||'')}${a.birth?' • '+e(birth(a.birth)):''} • ${e(a.discipline)}</span></button>`).join('');results.style.display='block';results.querySelectorAll('button').forEach(b=>b.onclick=()=>loadAthlete(b.dataset.id,b.dataset.name));}catch(err){status.textContent='Kunne ikke søke akkurat nå: '+String(err.message||err);}}
  async function loadAthlete(id,name){const status=document.querySelector('#athleteCompareStatus'),results=document.querySelector('#athleteCompareResults');results.style.display='none';status.textContent=`Henter og analyserer ${name}…`;try{const r=await fetch(`/api/athlete-search?action=analyse&type=${encodeURIComponent(currentType)}&id=${encodeURIComponent(id)}&name=${encodeURIComponent(name)}`,{cache:'no-store'}),a=await r.json();if(!r.ok)throw new Error(a.error||'Analysen mislyktes');state.selected=a;state.expected=D.events.map(ev=>predicted(a.events?.[ev]||[],ev));state.overrides=D.events.map(()=>null);status.textContent='';render();}catch(err){status.textContent='Kunne ikke analysere utøveren: '+String(err.message||err);}}
  function render(){const a=state.selected,out=document.querySelector('#athleteCompareOutput');if(!a||!out)return;const total=expectedTotal(state.expected);const rows=D.events.map((ev,i)=>{const count=(a.events?.[ev]||[]).length,p=state.expected[i];return `<tr><td>${e(ev)}</td><td style="color:${basisColor(count)};font-weight:800">${fmt(ev,p)}</td><td>${p==null?'—':scoreEvent(i,p)}</td><td>${count}</td></tr>`;}).join('');out.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:12px"><div><h3 style="margin:0">${e(a.name)}</h3><div style="color:#9fb2c6;margin-top:3px">${e(a.nation||'')}${a.birth?' • '+e(birth(a.birth)):''}</div></div><div style="display:flex;gap:8px;align-items:center"><div style="padding:9px 12px;border-radius:8px;background:#102a45"><small style="display:block;color:#9fb2c6">Forventet sluttpoeng</small><b style="font-size:22px">${total??'—'}</b></div><button id="whatIfBtn" type="button" style="padding:11px 16px;border:1px solid #6f4cff;border-radius:8px;background:#6f4cff;color:#fff;font-weight:900;cursor:pointer">Hva hvis?</button><button id="removeCompareBtn" type="button" style="padding:11px 14px;border:1px solid #456783;border-radius:8px;background:#0d2743;color:#fff;font-weight:800;cursor:pointer">Fjern</button></div></div><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Øvelse</th><th>Forventet resultat</th><th>Poeng</th><th>Resultater i grunnlaget</th></tr></thead><tbody>${rows}</tbody></table></div>`;document.querySelector('#whatIfBtn').onclick=openWhatIf;document.querySelector('#removeCompareBtn').onclick=()=>{state.selected=null;state.expected=[];state.overrides=[];out.innerHTML='';document.querySelector('#athleteCompareSearch').value='';};}
  function openWhatIf(){const a=state.selected;if(!a)return;const base=expectedTotal(state.expected);const fields=D.events.map((ev,i)=>`<div style="display:grid;grid-template-columns:120px 1fr 1fr;gap:8px;align-items:center;padding:7px 0;border-bottom:1px solid #1c3a56"><b>${e(ev)}</b><span style="color:#aebed0">Forventet: ${fmt(ev,state.expected[i])}</span><input data-whatif="${i}" value="${state.overrides[i]==null?'':e(fmt(ev,state.overrides[i]).replace(',','.'))}" placeholder="Skriv resultat" style="width:100%;box-sizing:border-box;padding:8px 9px;border-radius:6px;border:1px solid #456783;background:#07182b;color:#fff"></div>`).join('');document.querySelector('#modalContent').innerHTML=`<h2>${e(a.name)} – Hva hvis?</h2><p>Legg inn egne resultater i én eller flere øvelser. Tomme felt bruker den ordinære prognosen.</p><div style="margin-top:12px">${fields}</div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:16px"><div style="padding:10px 14px;background:#102a45;border-radius:8px"><small>Ordinær prognose</small><b style="display:block;font-size:22px">${base??'—'}</b></div><div style="padding:10px 14px;background:#102a45;border-radius:8px"><small>Hva hvis</small><b id="whatIfTotal" style="display:block;font-size:22px">${base??'—'}</b></div><div style="padding:10px 14px;background:#102a45;border-radius:8px"><small>Endring</small><b id="whatIfDiff" style="display:block;font-size:22px">0</b></div></div><div style="display:flex;gap:8px;margin-top:14px"><button id="whatIfReset" type="button" style="padding:10px 14px;border:1px solid #456783;border-radius:8px;background:#0d2743;color:#fff;font-weight:800;cursor:pointer">Nullstill</button><button id="whatIfApply" type="button" style="padding:10px 14px;border:0;border-radius:8px;background:#6f4cff;color:#fff;font-weight:900;cursor:pointer">Bruk scenario</button></div>`;const modal=document.querySelector('#modal');modal.classList.add('open');const recalc=()=>{document.querySelectorAll('[data-whatif]').forEach(inp=>{const i=Number(inp.dataset.whatif),v=parseInput(D.events[i],inp.value);state.overrides[i]=v;});const total=expectedTotal(currentValues()),diff=total!=null&&base!=null?total-base:null;document.querySelector('#whatIfTotal').textContent=total??'—';document.querySelector('#whatIfDiff').textContent=diff==null?'—':(diff>0?'+':'')+diff;};document.querySelectorAll('[data-whatif]').forEach(inp=>inp.addEventListener('input',recalc));document.querySelector('#whatIfReset').onclick=()=>{state.overrides=D.events.map(()=>null);openWhatIf();};document.querySelector('#whatIfApply').onclick=()=>{recalc();modal.classList.remove('open');renderScenario();};}
  function renderScenario(){render();const out=document.querySelector('#athleteCompareOutput'),base=expectedTotal(state.expected),total=expectedTotal(currentValues()),diff=total!=null&&base!=null?total-base:null;if(!out||!state.overrides.some(hasOverride))return;const note=document.createElement('div');note.style.cssText='margin:12px 0;padding:12px 14px;border:1px solid #6f4cff;border-radius:8px;background:#151c3b';note.innerHTML=`<b>Hva hvis-scenario:</b> ${total??'—'} poeng <span style="color:#b8aaff;font-weight:800">(${diff==null?'—':(diff>0?'+':'')+diff})</span> <button id="scenarioReset" type="button" style="margin-left:10px;padding:6px 10px;border:1px solid #456783;border-radius:6px;background:#0d2743;color:#fff;cursor:pointer">Nullstill</button>`;out.prepend(note);document.querySelector('#scenarioReset').onclick=()=>{state.overrides=D.events.map(()=>null);render();};}
  const nativeSetType=window.setType||setType;
  if(typeof nativeSetType==='function'){window.setType=function(type){nativeSetType(type);state.selected=null;state.expected=[];state.overrides=[];const box=document.querySelector('#athleteCompareBox');if(box)box.remove();inject();};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
