(function(){
  if(window.__MKA_I18N_V1)return;
  window.__MKA_I18N_V1=true;
  const LANGS={nb:{label:'Norsk',html:'nb'},en:{label:'English',html:'en'},de:{label:'Deutsch',html:'de'}};
  const CODES=['nb','en','de'];
  function language(){return localStorage.getItem('mka-language')||'nb';}
  function updateButtons(){const l=language();document.querySelectorAll('#mkaLanguageSwitcher button').forEach(b=>{const on=b.dataset.lang===l;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false');});}
  function setLanguage(l){if(!LANGS[l])return;localStorage.setItem('mka-language',l);document.documentElement.lang=LANGS[l].html;updateButtons();document.dispatchEvent(new CustomEvent('mka:languagechange',{detail:{language:l}}));if(window.MKA_I18N_FULL?.setLanguage)window.MKA_I18N_FULL.setLanguage(l);}
  function addSwitcher(){
    document.querySelector('#mkaLanguageSwitcher')?.remove();document.querySelector('#mka-i18n-style')?.remove();
    const st=document.createElement('style');st.id='mka-i18n-style';st.textContent=`#mkaLanguageSwitcher{margin-left:auto;display:flex;align-items:center;gap:8px;padding-left:14px}#mkaLanguageSwitcher button{position:relative;width:42px;height:30px;padding:0;border:1px solid #355b7c;border-radius:6px;background:#0b2038;overflow:hidden;cursor:pointer;opacity:.8}#mkaLanguageSwitcher button:hover,#mkaLanguageSwitcher button.active{opacity:1;border-color:#7b5cff;box-shadow:0 0 0 2px #6f4cff33}#mkaLanguageSwitcher .flag{position:absolute;inset:3px;border-radius:2px;overflow:hidden}#mkaLanguageSwitcher .nb .flag{background:linear-gradient(to bottom,#ba0c2f 0 100%)}#mkaLanguageSwitcher .nb .flag:before{content:'';position:absolute;left:28%;top:0;width:18%;height:100%;background:#fff}#mkaLanguageSwitcher .nb .flag:after{content:'';position:absolute;left:0;top:39%;width:100%;height:22%;background:#fff}#mkaLanguageSwitcher .nb i{position:absolute;z-index:2;background:#00205b}#mkaLanguageSwitcher .nb i.v{left:33%;top:0;width:8%;height:100%}#mkaLanguageSwitcher .nb i.h{left:0;top:45%;width:100%;height:10%}#mkaLanguageSwitcher .en .flag{background:#012169}#mkaLanguageSwitcher .en .flag:before{content:'';position:absolute;inset:0;background:linear-gradient(33deg,transparent 42%,#fff 43% 49%,#c8102e 50% 53%,#fff 54% 60%,transparent 61%),linear-gradient(-33deg,transparent 42%,#fff 43% 49%,#c8102e 50% 53%,#fff 54% 60%,transparent 61%)}#mkaLanguageSwitcher .en .flag:after{content:'';position:absolute;left:42%;top:0;width:16%;height:100%;background:#fff;box-shadow:-30px 10px 0 -7px #fff}#mkaLanguageSwitcher .en i.v{position:absolute;z-index:2;left:46%;top:0;width:8%;height:100%;background:#c8102e}#mkaLanguageSwitcher .en i.h{position:absolute;z-index:2;left:0;top:42%;width:100%;height:16%;background:#fff}#mkaLanguageSwitcher .en i.h:after{content:'';position:absolute;left:0;top:25%;width:100%;height:50%;background:#c8102e}#mkaLanguageSwitcher .de .flag{background:linear-gradient(to bottom,#000 0 33.33%,#dd0000 33.33% 66.66%,#ffce00 66.66% 100%)}@media(max-width:650px){#mkaLanguageSwitcher{gap:5px;padding-left:6px}#mkaLanguageSwitcher button{width:37px;height:27px}}`;document.head.appendChild(st);
    const w=document.createElement('div');w.id='mkaLanguageSwitcher';w.setAttribute('role','group');w.setAttribute('aria-label','Språk');CODES.forEach(code=>{const b=document.createElement('button');b.type='button';b.dataset.lang=code;b.className=code;b.title=LANGS[code].label;b.setAttribute('aria-label',LANGS[code].label);b.innerHTML='<span class="flag"></span><i class="v"></i><i class="h"></i>';b.onclick=()=>setLanguage(code);w.appendChild(b);});(document.querySelector('.topbar')||document.querySelector('header')||document.body).appendChild(w);updateButtons();
  }
  window.MKA_I18N={get language(){return language();},setLanguage,t:(s)=>s,translate:()=>{}};
  addSwitcher();
})();