const SOURCE='https://worldathletics.nimarion.de';
const WA='https://worldathletics.org';
const YEARS=new Set([2026,2025]);
const CUTOFF=Date.parse('2026-08-12T00:00:00Z');
const EVENT_MAP=[[/^100 metres$/i,'100m'],[/^100m$/i,'100m'],[/^long jump$/i,'Lengde'],[/^shot put$/i,'Kule'],[/^high jump$/i,'Høyde'],[/^400 metres$/i,'400m'],[/^400m$/i,'400m'],[/^110 metres hurdles$/i,'110mh'],[/^110m hurdles$/i,'110mh'],[/^discus throw$/i,'Diskos'],[/^pole vault$/i,'Stav'],[/^javelin throw$/i,'Spyd'],[/^1500 metres$/i,'1500m'],[/^1500m$/i,'1500m'],[/^100 metres hurdles$/i,'100mh'],[/^100m hurdles$/i,'100mh'],[/^200 metres$/i,'200m'],[/^200m$/i,'200m'],[/^800 metres$/i,'800m'],[/^800m$/i,'800m']];
const EVENTS={men:['100m','Lengde','Kule','Høyde','400m','110mh','Diskos','Stav','Spyd','1500m'],women:['100mh','Høyde','Kule','200m','Lengde','Spyd','800m']};
const WIND_EVENTS=new Set(['100m','Lengde','110mh','100mh','200m']);
const SENIOR_DISCIPLINES={men:{'100m':['100 Metres','100m'],Lengde:['Long Jump'],Kule:['Shot Put'],Høyde:['High Jump'],'400m':['400 Metres','400m'],'110mh':['110 Metres Hurdles','110m Hurdles'],Diskos:['Discus Throw'],Stav:['Pole Vault'],Spyd:['Javelin Throw'],'1500m':['1500 Metres','1500m']},women:{'100mh':['100 Metres Hurdles','100m Hurdles'],Høyde:['High Jump'],Kule:['Shot Put'],'200m':['200 Metres','200m'],Lengde:['Long Jump'],Spyd:['Javelin Throw'],'800m':['800 Metres','800m']}};
const VALID_RANGES={men:{'100m':[9,13.5],Lengde:[5,9.5],Kule:[8,22],Høyde:[1.4,2.5],'400m':[43,60],'110mh':[12,20],Diskos:[20,70],Stav:[3,6.5],Spyd:[30,90],'1500m':[210,360]},women:{'100mh':[11.5,20],Høyde:[1.3,2.2],Kule:[7,20],'200m':[21,32],Lengde:[4.5,8],Spyd:[25,75],'800m':[110,190]}};
function appEvent(v){for(const[rx,n]of EVENT_MAP)if(rx.test(String(v||'').trim()))return n;return null;}
function exactSeniorDiscipline(r,event,type){const d=String(r?.discipline||r?.event||'').trim().replace(/\s+/g,' ').toLowerCase();return (SENIOR_DISCIPLINES[type]?.[event]||[]).some(x=>x.toLowerCase()===d);}
function parseMark(mark,event){const s=String(mark??'').trim().replace(',','.');if(!s||/^(DNS|DNF|DQ|NM|NH|NT)$/i.test(s))return null;if((event==='1500m'||event==='800m')&&s.includes(':')){const p=s.split(':').map(Number);if(p.length===2&&p.every(Number.isFinite))return p[0]*60+p[1];}const n=Number(s.replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null;}
function dateValue(d){const t=Date.parse(String(d||''));return Number.isFinite(t)?t:0;}
function yearOf(d){const m=String(d||'').match(/(?:19|20)\d{2}/);return m?Number(m[0]):0;}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/æ/gi,'ae').replace(/ø/gi,'o').replace(/å/gi,'a').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function tokens(v){return norm(v).split(' ').filter(Boolean);}
function matchesPartial(name,q){const nt=tokens(name),qt=tokens(q);return qt.length>0&&qt.every(q=>nt.some(n=>n===q||n.startsWith(q)||n.includes(q)));}
function matchScore(name,q){const n=norm(name),nt=tokens(name),qt=tokens(q);if(n===norm(q))return 0;if(qt.length===1&&nt.includes(qt[0]))return 1;if(qt.every(q=>nt.some(t=>t===q)))return 2;if(qt.every(q=>nt.some(t=>t.startsWith(q))))return 3;if(qt.every(q=>nt.some(t=>t.includes(q))))return 4;return 9;}
function seniorOnly(r,event,type){if(!exactSeniorDiscipline(r,event,type))return false;const text=[r?.discipline,r?.category,r?.competition,r?.race,r?.implement,r?.ageCategory,r?.event].filter(Boolean).join(' ').toLowerCase();if(/\b(u18|u20|junior|youth)\b/.test(text))return false;return true;}
function venueText(v){if(v==null)return'';if(typeof v==='string'||typeof v==='number')return String(v).trim();if(typeof v!=='object')return'';return [v.venueName,v.stadium,v.name,v.city,v.town,v.place,v.locationName,v.countryCode,v.country?.code,v.country?.name].map(venueText).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join(', ');}
function venueOf(r){return venueText(r?.location)||venueText(r?.venue)||venueText(r?.competitionVenue)||'';}
function indoorOf(r){const text=[r?.competition,r?.meeting,venueOf(r),r?.category,r?.venueName,r?.stadium].filter(Boolean).join(' ').toLowerCase();if(/indoor|indoors|short track|\(i\)/.test(text))return true;const explicit=[r?.indoor,r?.isIndoor,r?.environment,r?.venueType,r?.competitionType,r?.stadiumType].filter(v=>v!==undefined&&v!==null).map(v=>String(v).toLowerCase()).join(' ');if(/(^|\b)(true|indoor|indoors|short track)(\b|$)/.test(explicit))return true;if(/(^|\b)(false|outdoor|outdoors)(\b|$)/.test(explicit))return false;return false;}
function windLegal(r,event){if(!WIND_EVENTS.has(event)||indoorOf(r))return true;if(r?.legal===false)return false;const raw=String(r?.wind??r?.windReading??r?.resultWind??'').trim().replace(',','.');if(!raw)return r?.legal===true;const w=Number(raw.replace(/[^0-9.+-]/g,''));return Number.isFinite(w)&&w<=2.0;}
async function json(url){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Mangekampanalyse/2.0'},cf:{cacheTtl:60,cacheEverything:true}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function text(url){const r=await fetch(url,{headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'Mozilla/5.0 Mangekampanalyse/2.0'},cf:{cacheTtl:60,cacheEverything:true}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text();}
function athleteName(a){return String(a?.name||a?.fullName||[a?.firstname??a?.firstName,a?.lastname??a?.lastName].filter(Boolean).join(' ')||'').trim();}
function athleteNation(a){return String(a?.countryCode||a?.country||a?.nationality||a?.federation||'').trim();}
function athleteBirth(a){return String(a?.birthdate||a?.dateOfBirth||a?.birthDate||a?.dob||a?.birth||'').trim();}
function athleteGender(a){const raw=String(a?.gender??a?.sex??a?.genderCode??a?.sexCode??'').trim().toLowerCase();if(!raw)return'';if(['m','male','man','men'].includes(raw))return'men';if(['f','female','woman','women','w'].includes(raw))return'women';return'';}
function combinedFlags(rows){let hept=false,deca=false;for(const r of Array.isArray(rows)?rows:[]){const t=String(r?.discipline||r?.event||r?.competition||'');if(/heptathlon/i.test(t))hept=true;if(/decathlon/i.test(t))deca=true;}return{hept,deca};}
function eligibleCombinedAthlete(a,rows,type){const g=athleteGender(a);if(g&&g!==type)return false;const f=combinedFlags(rows);if(type==='men')return f.deca;if(!f.hept)return false;if(g==='women')return true;return !f.deca;}
function samePerformance(a,b){return Number(a.mark).toFixed(3)===Number(b.mark).toFixed(3)&&String(a.date||'')===String(b.date||'')&&norm(a.venue)===norm(b.venue);}
function uniqueRecent(rows){const kept=[];for(const r of [...rows].sort((a,b)=>dateValue(b.date)-dateValue(a.date))){if(!YEARS.has(Number(r.year)))continue;if(kept.some(x=>samePerformance(x,r)))continue;kept.push(r);}return kept;}
function finalize(grouped){const out={};for(const[e,rows]of Object.entries(grouped)){const all=uniqueRecent(rows),outdoor=all.filter(r=>!r.indoor).sort((a,b)=>dateValue(b.date)-dateValue(a.date)),indoor=all.filter(r=>r.indoor).sort((a,b)=>dateValue(b.date)-dateValue(a.date)),kept=outdoor.slice(0,4);if(kept.length<4){for(const r of indoor){if(kept.length===4)break;kept.push(r);}}out[e]=kept;}return out;}
function applyVerifiedCorrections(data){if(!data?.events)return data;const isJonathan=String(data.id||'')==='14989292'||/jonathan\s+hertwig/i.test(String(data.name||''));if(!isJonathan)return data;const verified={mark:7.21,display:'7.21',venue:'Randal Tyson Indoor Center, Fayetteville, AR',year:2026,date:'2026-01-30',competition:'Razorback Invitational',wind:'',legal:true,indoor:true};const rows=Array.isArray(data.events.Lengde)?data.events.Lengde:[];const outdoor=rows.filter(r=>!r?.indoor&&String(r?.date)!=='2026-01-30').sort((a,b)=>dateValue(b.date)-dateValue(a.date));data.events.Lengde=[...outdoor.slice(0,3),verified].sort((a,b)=>dateValue(b.date)-dateValue(a.date));return data;}
async function resultsFor(id){return json(`${SOURCE}/athletes/${encodeURIComponent(id)}/results`).catch(()=>[]);}
function addUnique(all,a){if(a?.id&&!all.some(x=>String(x.id)===String(a.id)))all.push(a);}
function titleCaseSlug(s){return decodeURIComponent(String(s||'')).split('-').filter(Boolean).map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ');}
async function waSearch(q){const html=await text(`${WA}/athletes-home?query=${encodeURIComponent(q)}`).catch(()=> '');if(!html)return[];const out=[];const rx=/href=["'](?:https:\/\/worldathletics\.org)?\/athletes\/([^\/"']+)\/([^"']+?)-(\d{7,})["']/gi;let m;while((m=rx.exec(html))){addUnique(out,{id:String(m[3]),name:titleCaseSlug(m[2]),countryCode:String(m[1]||'').toUpperCase()});if(out.length>=250)break;}return out;}
async function rawSearch(q){const all=[];const terms=[q,...tokens(q)];for(const term of [...new Set(terms.filter(x=>String(x).trim().length>=2))]){const [api,wa]=await Promise.all([json(`${SOURCE}/athletes/search?name=${encodeURIComponent(term)}`).catch(()=>[]),waSearch(term)]);for(const a of Array.isArray(api)?api:[])addUnique(all,a);for(const a of wa)addUnique(all,a);}return all.filter(a=>matchesPartial(athleteName(a),q)).sort((a,b)=>matchScore(athleteName(a),q)-matchScore(athleteName(b),q)||athleteName(a).localeCompare(athleteName(b),'nb'));}
async function searchAthletes(q,type){const found=await rawSearch(q);const candidates=found.filter(a=>a?.id&&(!athleteGender(a)||athleteGender(a)===type)).slice(0,200);const checked=[];for(let i=0;i<candidates.length;i+=25){const batch=await Promise.all(candidates.slice(i,i+25).map(async a=>{const rows=await resultsFor(a.id);if(!eligibleCombinedAthlete(a,rows,type))return null;return{id:a.id,name:athleteName(a),nation:athleteNation(a),birth:athleteBirth(a),discipline:type==='women'?'Sjukamp':'Tikamp',score:matchScore(athleteName(a),q)};}));checked.push(...batch.filter(Boolean));if(checked.length>=30)break;}return checked.sort((a,b)=>a.score-b.score||a.name.localeCompare(b.name,'nb')).slice(0,30).map(({score,...a})=>a);}
async function analyseAthlete(id,type,nameHint){const rows=await resultsFor(id);const search=await rawSearch(nameHint||'');const meta=(Array.isArray(search)?search:[]).find(a=>String(a?.id)===String(id))||{};if(!eligibleCombinedAthlete(meta,rows,type))throw new Error(type==='women'?'Utøveren er ikke en relevant kvinnelig sjukamputøver.':'Utøveren er ikke en relevant mannlig tikamputøver.');const grouped={};for(const r of rows){const event=appEvent(r?.discipline);if(!event||!EVENTS[type].includes(event)||!seniorOnly(r,event,type)||!windLegal(r,event))continue;const mark=parseMark(r?.mark,event),date=String(r?.date||''),t=dateValue(date),year=yearOf(date),range=VALID_RANGES[type]?.[event],indoor=indoorOf(r);if(mark==null||!t||t>=CUTOFF||!YEARS.has(year)||(range&&(mark<range[0]||mark>range[1])))continue;(grouped[event]||=[]).push({mark,display:String(r?.mark||''),venue:venueOf(r),year,date,competition:String(r?.competition||r?.meeting||''),wind:String(r?.wind??r?.windReading??r?.resultWind??''),legal:true,indoor});}const data={id:String(id),name:athleteName(meta)||nameHint||`Utøver ${id}`,nation:athleteNation(meta),birth:athleteBirth(meta),type,events:finalize(grouped)};return applyVerifiedCorrections(data);}
function response(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
export async function onRequestGet({request}){const u=new URL(request.url),action=u.searchParams.get('action')||'search',type=u.searchParams.get('type')==='women'?'women':'men';try{if(action==='search'){const q=String(u.searchParams.get('q')||'').trim();if(q.length<2)return response({athletes:[]});return response({type,athletes:await searchAthletes(q,type)});}if(action==='analyse'){const id=String(u.searchParams.get('id')||'').trim(),name=String(u.searchParams.get('name')||'').trim();if(!id)return response({error:'Mangler utøver-ID'},400);return response(await analyseAthlete(id,type,name));}return response({error:'Ukjent handling'},400);}catch(e){return response({error:String(e?.message||e)},502);}}