const SOURCE='https://worldathletics.nimarion.de';
const YEARS=new Set([2026,2025]);
const CUTOFF=Date.parse('2026-08-12T00:00:00Z');
const EVENT_MAP=[[/^100 metres$/i,'100m'],[/^100m$/i,'100m'],[/long jump/i,'Lengde'],[/shot put/i,'Kule'],[/high jump/i,'Høyde'],[/^400 metres$/i,'400m'],[/^400m$/i,'400m'],[/110 metres hurdles/i,'110mh'],[/110m hurdles/i,'110mh'],[/discus throw/i,'Diskos'],[/pole vault/i,'Stav'],[/javelin throw/i,'Spyd'],[/^1500 metres$/i,'1500m'],[/^1500m$/i,'1500m'],[/100 metres hurdles/i,'100mh'],[/100m hurdles/i,'100mh'],[/^200 metres$/i,'200m'],[/^200m$/i,'200m'],[/^800 metres$/i,'800m'],[/^800m$/i,'800m']];
const EVENTS={men:['100m','Lengde','Kule','Høyde','400m','110mh','Diskos','Stav','Spyd','1500m'],women:['100mh','Høyde','Kule','200m','Lengde','Spyd','800m']};
const WIND_EVENTS=new Set(['100m','Lengde','110mh','100mh','200m']);
const VALID_RANGES={men:{'100m':[9,13.5],Lengde:[5,9.5],Kule:[8,22],Høyde:[1.4,2.5],'400m':[43,60],'110mh':[12,20],Diskos:[20,70],Stav:[3,6.5],Spyd:[30,90],'1500m':[210,360]},women:{'100mh':[11.5,20],Høyde:[1.3,2.2],Kule:[7,20],'200m':[21,32],Lengde:[4.5,8],Spyd:[25,75],'800m':[110,190]}};
function appEvent(v){for(const[rx,n]of EVENT_MAP)if(rx.test(String(v||'').trim()))return n;return null;}
function parseMark(mark,event){const s=String(mark??'').trim().replace(',','.');if(!s||/^(DNS|DNF|DQ|NM|NH|NT)$/i.test(s))return null;if((event==='1500m'||event==='800m')&&s.includes(':')){const p=s.split(':').map(Number);if(p.length===2&&p.every(Number.isFinite))return p[0]*60+p[1];}const n=Number(s.replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null;}
function dateValue(d){const t=Date.parse(String(d||''));return Number.isFinite(t)?t:0;}
function yearOf(d){const m=String(d||'').match(/(?:19|20)\d{2}/);return m?Number(m[0]):0;}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function seniorOnly(r,event,type){const text=[r?.discipline,r?.category,r?.competition,r?.race,r?.implement,r?.ageCategory,r?.event].filter(Boolean).join(' ').toLowerCase();if(/\b(u18|u20|junior|youth)\b/.test(text))return false;if(type==='men'){if(event==='Kule'&&/(6\s*kg|5\s*kg)/i.test(text))return false;if(event==='Diskos'&&/(1\.75\s*kg|1\.5\s*kg)/i.test(text))return false;if(event==='110mh'&&/(0\.991|99\.1|0\.914|91\.4)/i.test(text))return false;}return true;}
function windLegal(r,event){if(!WIND_EVENTS.has(event))return true;if(r?.legal===false)return false;const raw=String(r?.wind??r?.windReading??'').trim().replace(',','.');if(!raw)return r?.legal===true;const w=Number(raw.replace(/[^0-9.+-]/g,''));return Number.isFinite(w)&&w<=2.0;}
function venueText(v){if(v==null)return'';if(typeof v==='string'||typeof v==='number')return String(v).trim();if(typeof v!=='object')return'';return [v.venueName,v.stadium,v.name,v.city,v.town,v.place,v.locationName,v.countryCode,v.country?.code,v.country?.name].map(venueText).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join(', ');}
function venueOf(r){return venueText(r?.location)||venueText(r?.venue)||venueText(r?.competitionVenue)||'';}
async function json(url){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Mangekampanalyse/2.0'},cf:{cacheTtl:60,cacheEverything:true}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function athleteName(a){return String(a?.name||a?.fullName||[a?.firstName,a?.lastName].filter(Boolean).join(' ')||'').trim();}
function athleteNation(a){return String(a?.countryCode||a?.country||a?.nationality||a?.federation||'').trim();}
function athleteBirth(a){return String(a?.dateOfBirth||a?.birthDate||a?.dob||a?.birth||'').trim();}
function combinedText(a){return [a?.discipline,a?.disciplines,a?.event,a?.events,a?.primaryDiscipline].flat().filter(Boolean).join(' ').toLowerCase();}
function isCombinedCandidate(a,type){const t=combinedText(a);if(!t)return true;return type==='women'?/heptathlon/.test(t):/decathlon/.test(t);}
function hasCombinedResult(rows,type){const rx=type==='women'?/heptathlon/i:/decathlon/i;return (Array.isArray(rows)?rows:[]).some(r=>rx.test(String(r?.discipline||r?.event||'')));}
function samePerformance(a,b){return Number(a.mark).toFixed(3)===Number(b.mark).toFixed(3)&&String(a.date||'')===String(b.date||'')&&norm(a.venue)===norm(b.venue);}
function finalize(grouped){const out={};for(const[e,rows]of Object.entries(grouped)){const kept=[];for(const r of rows.sort((a,b)=>dateValue(b.date)-dateValue(a.date))){if(!YEARS.has(Number(r.year)))continue;if(kept.some(x=>samePerformance(x,r)))continue;kept.push(r);if(kept.length===4)break;}out[e]=kept;}return out;}
async function resultsFor(id){return json(`${SOURCE}/athletes/${encodeURIComponent(id)}/results`).catch(()=>[]);}
async function searchAthletes(q,type){const found=await json(`${SOURCE}/athletes/search?name=${encodeURIComponent(q)}`);const candidates=(Array.isArray(found)?found:[]).filter(a=>a?.id&&isCombinedCandidate(a,type)).slice(0,10);const checked=[];for(const a of candidates){const text=combinedText(a);let ok=type==='women'?/heptathlon/.test(text):/decathlon/.test(text);if(!text){const rows=await resultsFor(a.id);ok=hasCombinedResult(rows,type);}if(ok)checked.push({id:a.id,name:athleteName(a),nation:athleteNation(a),birth:athleteBirth(a),discipline:type==='women'?'Sjukamp':'Tikamp'});if(checked.length>=8)break;}return checked;}
async function analyseAthlete(id,type,nameHint){const rows=await resultsFor(id);if(!hasCombinedResult(rows,type))throw new Error(type==='women'?'Utøveren har ingen registrerte sjukampresultater.':'Utøveren har ingen registrerte tikampresultater.');const grouped={};for(const r of rows){const event=appEvent(r?.discipline);if(!event||!EVENTS[type].includes(event)||!seniorOnly(r,event,type)||!windLegal(r,event))continue;const mark=parseMark(r?.mark,event),date=String(r?.date||''),t=dateValue(date),year=yearOf(date),range=VALID_RANGES[type]?.[event];if(mark==null||!t||t>=CUTOFF||!YEARS.has(year)||(range&&(mark<range[0]||mark>range[1])))continue;(grouped[event]||=[]).push({mark,display:String(r?.mark||''),venue:venueOf(r),year,date,competition:String(r?.competition||r?.meeting||''),wind:String(r?.wind??r?.windReading??''),legal:true});}
const search=await json(`${SOURCE}/athletes/search?name=${encodeURIComponent(nameHint||'')}`).catch(()=>[]);const meta=(Array.isArray(search)?search:[]).find(a=>String(a?.id)===String(id))||{};return{id:String(id),name:athleteName(meta)||nameHint||`Utøver ${id}`,nation:athleteNation(meta),birth:athleteBirth(meta),type,events:finalize(grouped)};}
function response(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=60'}});}
export async function onRequestGet({request}){const u=new URL(request.url),action=u.searchParams.get('action')||'search',type=u.searchParams.get('type')==='women'?'women':'men';try{if(action==='search'){const q=String(u.searchParams.get('q')||'').trim();if(q.length<2)return response({athletes:[]});return response({type,athletes:await searchAthletes(q,type)});}if(action==='analyse'){const id=String(u.searchParams.get('id')||'').trim(),name=String(u.searchParams.get('name')||'').trim();if(!id)return response({error:'Mangler utøver-ID'},400);return response(await analyseAthlete(id,type,name));}return response({error:'Ukjent handling'},400);}catch(e){return response({error:String(e?.message||e)},502);}}
