const SOURCE='https://worldathletics.nimarion.de';
const MEN=['Johannes Erm','Sander Skotheim','Leo Neugebauer','Niklas Kaul','Makenson Gletty','Sven Roosen','Karel Tilga','Tomas Järvinen','Amadeus Gräber','Rasmus Roosleht','Dario Dester','Vilém Stráský','Antoine Ferranti','Ondřej Kopecký','Andrin Huber','Risto Lillemets','Jeff Tesselaar','Luuk Pelkmans','Edgaras Benkunskas','Dai Keïta','Zsombor Gálpál','Nino Portmann','Alberto Nonino','Leon Krummenacher','Emil Uhlin','Jip de Greef'];
const WOMEN=['Annik Kälin',"Kate O'Connor",'Emma Oosterwegel','Sofie Dokter','Katarina Johnson-Thompson','Sophie Weißenberg','Sandrina Sprengel','Adrianna Sułek-Schubert','Sveva Gerevini',"Jade O'Dowda",'Vanessa Grimm','Szabina Szűcs','Beatričė Juškevičiūtė','Noor Vidts','María Vicente','Lovisa Karlsson','Jéssica Barreira','Sarolta Kriszt','Jana Koščak','Erika Wärff','Verena Mayr','Sofia Cosculluela','Anastasia Ntragkomirova','Adéla Tkáčová'];
const EVENT_MAP=[[/^100 metres$/i,'100m'],[/^100m$/i,'100m'],[/long jump/i,'Lengde'],[/shot put/i,'Kule'],[/high jump/i,'Høyde'],[/^400 metres$/i,'400m'],[/^400m$/i,'400m'],[/110 metres hurdles/i,'110mh'],[/110m hurdles/i,'110mh'],[/discus throw/i,'Diskos'],[/pole vault/i,'Stav'],[/javelin throw/i,'Spyd'],[/^1500 metres$/i,'1500m'],[/^1500m$/i,'1500m'],[/100 metres hurdles/i,'100mh'],[/100m hurdles/i,'100mh'],[/^200 metres$/i,'200m'],[/^200m$/i,'200m'],[/^800 metres$/i,'800m'],[/^800m$/i,'800m']];
const WIND_EVENTS=new Set(['100m','Lengde','110mh','100mh','200m']);
const YEARS=[2026,2025];
const CUTOFF=Date.parse('2026-08-12T00:00:00Z');
const VALID_RANGES={men:{'100m':[9,13.5],Lengde:[5,9.5],Kule:[8,22],Høyde:[1.4,2.5],'400m':[43,60],'110mh':[12,20],Diskos:[20,70],Stav:[3,6.5],Spyd:[30,90],'1500m':[210,360]},women:{'100mh':[11.5,20],Høyde:[1.3,2.2],Kule:[7,20],'200m':[21,32],Lengde:[4.5,8],Spyd:[25,75],'800m':[110,190]}};
function appEvent(v){for(const[rx,n]of EVENT_MAP)if(rx.test(String(v||'').trim()))return n;return null;}
function parseMark(mark,event){const s=String(mark??'').trim().replace(',','.');if(!s||/^(DNS|DNF|DQ|NM|NH|NT)$/i.test(s))return null;if((event==='1500m'||event==='800m')&&s.includes(':')){const p=s.split(':').map(Number);if(p.length===2&&p.every(Number.isFinite))return p[0]*60+p[1];}const n=Number(s.replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:null;}
function markPlausible(mark,event,type){const range=VALID_RANGES[type]?.[event];return !range||(mark>=range[0]&&mark<=range[1]);}
function yearOf(d){const m=String(d||'').match(/(?:19|20)\d{2}/);return m?m[0]:'';}
function dateValue(d){const t=Date.parse(String(d||''));return Number.isFinite(t)?t:0;}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\([^)]*\)/g,'').replace(/\b(stadium|stadion|field|arena|sportzentrum|athletikstadion)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();}
function seniorOnly(r,event,type){const text=[r?.discipline,r?.category,r?.competition,r?.race,r?.implement,r?.ageCategory,r?.event].filter(Boolean).join(' ').toLowerCase();if(/\b(u18|u20|junior|youth)\b/.test(text))return false;if(type==='men'){if(event==='Kule'&&/(6\s*kg|5\s*kg)/i.test(text))return false;if(event==='Diskos'&&/(1\.75\s*kg|1\.5\s*kg)/i.test(text))return false;if(event==='110mh'&&/(0\.991|99\.1|0\.914|91\.4)/i.test(text))return false;}return true;}
function windLegal(r,event){if(!WIND_EVENTS.has(event))return true;if(r?.legal===false)return false;const raw=String(r?.wind??r?.windReading??'').trim().replace(',','.');if(!raw)return r?.legal===true;const w=Number(raw.replace(/[^0-9.+-]/g,''));return Number.isFinite(w)&&w<=2.0;}
function venueText(v){if(v==null)return'';if(typeof v==='string'||typeof v==='number'){const s=String(v).trim();return s==='[object Object]'?'':s;}if(typeof v!=='object')return'';const vals=[v.venueName,v.stadium,v.name,v.city,v.town,v.place,v.locationName,v.countryCode,v.country?.code,v.country?.name];const out=[];for(const x of vals){const s=venueText(x);if(s&&!out.includes(s))out.push(s);}return out.join(', ');}
function venueOf(r){return venueText(r?.location)||venueText(r?.venue)||venueText(r?.competitionVenue)||'';}
async function json(url){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Mangekampanalyse/1.0'},cf:{cacheTtl:60,cacheEverything:true}});if(!r.ok)throw new Error(`HTTP ${r.status} ${url}`);return r.json();}
function chooseAthlete(found,name){if(!Array.isArray(found)||!found.length)return null;const n=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,' ').trim().toLowerCase();const target=n(name);return found.find(a=>n(a.name||a.fullName)===target)||found[0];}
function samePerformance(a,b){if(Number(a.mark).toFixed(3)!==Number(b.mark).toFixed(3))return false;if(a.date&&b.date)return String(a.date)===String(b.date);return String(a.year)===String(b.year)&&norm(a.venue)===norm(b.venue)&&norm(a.competition)===norm(b.competition);}
function finalize(grouped){const out={};for(const[e,rows]of Object.entries(grouped)){const kept=[];for(const r of rows.sort((a,b)=>dateValue(b.date)-dateValue(a.date)||String(b.venue||'').length-String(a.venue||'').length)){if(!YEARS.includes(Number(r.year)))continue;if(kept.some(x=>samePerformance(x,r)))continue;kept.push(r);if(kept.length===4)break;}out[e]=kept;}return out;}
async function athleteHistory(name,type){try{const found=await json(`${SOURCE}/athletes/search?name=${encodeURIComponent(name)}`);const athlete=chooseAthlete(found,name);if(!athlete?.id)return{name,error:'Athlete not found',events:{}};const batches=await Promise.all(YEARS.map(y=>json(`${SOURCE}/athletes/${athlete.id}/results?year=${y}`).catch(()=>[])));const grouped={};for(const r of batches.flat()){const e=appEvent(r?.discipline);if(!e||!seniorOnly(r,e,type)||!windLegal(r,e))continue;const mark=parseMark(r?.mark,e);if(mark==null||!markPlausible(mark,e,type))continue;const date=String(r?.date||'');const t=dateValue(date);if(!t||t>=CUTOFF)continue;const venue=venueOf(r);if(!venue)continue;(grouped[e]||=[]).push({mark,display:String(r.mark||''),venue,year:yearOf(date),date,competition:String(r.competition||r.meeting||''),wind:String(r.wind??r.windReading??''),legal:true,source:'world-athletics'});}return{name,id:athlete.id,events:finalize(grouped)};}catch(e){return{name,error:String(e?.message||e),events:{}};}}
async function mapLimited(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out;}
export async function onRequestGet({request}){const u=new URL(request.url);const type=u.searchParams.get('type')==='women'?'women':'men';const names=type==='women'?WOMEN:MEN;try{const data=await mapLimited(names,3,n=>athleteHistory(n,type));const coverage=data.map(a=>({name:a.name,events:Object.fromEntries(Object.entries(a.events||{}).map(([e,r])=>[e,r.length])),error:a.error||null}));return new Response(JSON.stringify({source:'World Athletics verified 2025-2026 results before Birmingham 2026',updatedAt:new Date().toISOString(),type,athletes:data,coverage}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=60'}});}catch(e){return new Response(JSON.stringify({error:String(e?.message||e)}),{status:502,headers:{'content-type':'application/json'}});}}
