const TRPC='https://proxy.european-athletics.com/trpc';
const COMPETITION_CODE='ECH26';
const UNIT='ATHWHEPTATH-----------JT--A00100--';
function enc(payload){return encodeURIComponent(JSON.stringify({json:payload}));}
function rowsFromPayload(payload){if(!payload)return[];if(Array.isArray(payload.athletes))return payload.athletes;if(Array.isArray(payload.results))return payload.results;const found=[];function walk(v,d=0){if(v==null||d>8)return;if(Array.isArray(v)){for(const x of v){if(x&&typeof x==='object'&&(x.athleteId!=null||x.federationId!=null)&&x.result!=null)found.push(x);else walk(x,d+1);}return;}if(typeof v==='object')for(const x of Object.values(v))walk(x,d+1);}walk(payload);return found;}
function scalar(v,d=0){if(v==null||d>4)return null;if(typeof v!=='object')return v;if(Array.isArray(v))return null;for(const k of ['result','results','performance','mark','value','distance','bestResult','resultValue','bestMark']){if(v[k]!=null){const s=scalar(v[k],d+1);if(s!=null&&String(s).trim()!=='')return s;}}return null;}
function attemptsFromRow(row){const out=[];const seen=new Set();function add(v,roundHint=null){if(v==null)return;if(typeof v!=='object'){const s=String(v).trim();if(!s)return;const key=`${roundHint||out.length+1}:${s}`;if(!seen.has(key)){seen.add(key);out.push({attemptId:Number(roundHint||out.length+1),result:s});}return;}const s=scalar(v);if(s!=null&&String(s).trim()!==''){const round=Number(v.attemptId??v.round??v.roundNo??v.trial??v.trialNo??roundHint??out.length+1);const result=String(s).trim();const key=`${round}:${result}`;if(!seen.has(key)){seen.add(key);out.push({attemptId:round,result,wind:String(v.wind??v.resultWind??'').trim()});}}}
function walk(v,d=0,key=''){if(v==null||d>7)return;if(Array.isArray(v)){if(/attempt|trial|throw|series|result|performance/i.test(key)){v.forEach((x,i)=>add(x,i+1));}for(const x of v)walk(x,d+1,key);return;}if(typeof v==='object'){for(const [k,x] of Object.entries(v))walk(x,d+1,k);}}
for(const k of ['attempts','trials','throws','series','attemptResults','performances','results']){const v=row?.[k];if(Array.isArray(v))v.forEach((x,i)=>add(x,i+1));}
if(!out.length)walk(row,0,'row');
out.sort((a,b)=>(a.attemptId||0)-(b.attemptId||0));return out.slice(0,6);}
export async function onRequestGet(){try{const input=enc({event:UNIT,competitionCode:COMPETITION_CODE,isSummary:false});const r=await fetch(`${TRPC}/liveResults.getCombinedEventResultsFeed?input=${input}`,{headers:{'X-Client-Platform':'Desktop','Accept':'application/json','User-Agent':'Mozilla/5.0'},cf:{cacheTtl:0,cacheEverything:false}});if(!r.ok)throw new Error(`EA HTTP ${r.status}`);const body=await r.json();const rows=rowsFromPayload(body?.result?.data?.json??null).map(row=>({athleteId:String(row.athleteId??row.federationId??''),bib:String(row.bib??''),result:String(row.result??row.performance??row.mark??''),points:row.combinedResult?.points??row.points??null,attempts:attemptsFromRow(row)})).filter(x=>x.athleteId&&x.result);return new Response(JSON.stringify({count:rows.length,rows,updatedAt:new Date().toISOString()}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0','access-control-allow-origin':'*'}});}catch(e){return new Response(JSON.stringify({error:String(e?.message||e),count:0,rows:[]}),{status:502,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}}
